# This workflow will install Python dependencies and poetry
# It runs pytest, flake8 and black

name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
        poetry-version: ["1.1.15"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry install
      - name: Lint with flake8
        run: poetry run flake8
      - name: Test with pytest
        run: poetry run pytest
      - name: Check code style
        run: poetry run black --check --diff .
